services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: pot_postgres_db
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: POT_db
    volumes:
      # Persists data to local machine so that data isn't lost when the container stops
      - postgres_data:/var/lib/postgresql/data/
      - ./init-db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
